import streamlit as st
import pandas as pd
import altair as alt
import numpy as np

# -----------------------------------------------------------------------------
# 1. PAGE CONFIGURATION & FIXES
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="Geo-Credit Strategic Dashboard",
    page_icon="🏦",
    layout="wide",
    initial_sidebar_state="expanded"
)

# [FIX] CRITICAL: Matikan limit baris Altair agar bisa render >5000 desa
alt.data_transformers.disable_max_rows()

# Professional Corporate Styling
st.markdown("""
<style>
    .stTabs [data-baseweb="tab-list"] { gap: 10px; }
    .stTabs [data-baseweb="tab"] {
        height: 50px; white-space: pre-wrap; background-color: #f0f2f6; border-radius: 5px 5px 0 0; gap: 1px; padding-top: 10px; padding-bottom: 10px;
    }
    .stTabs [aria-selected="true"] { background-color: #FFFFFF; border-top: 3px solid #2e7bcf; }
    .metric-card { background-color: #ffffff; border: 1px solid #e0e0e0; padding: 15px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
    h3 { font-size: 20px !important; color: #333; }
</style>
""", unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# 2. DATA ENGINE (LOADING & PROCESSING)
# -----------------------------------------------------------------------------
@st.cache_data
def load_data_engine():
    try:
        df = pd.read_csv('Prototype Jawa Tengah.csv')
    except FileNotFoundError:
        return None

    # --- A. CLEANING ---
    df.columns = [col.replace('potensi_wilayah_kel_podes_pdrb_sekda_current.', '') for col in df.columns]
    
    # Rename Critical Columns
    df.rename(columns={
        'nama_kabupaten': 'Kabupaten', 'nama_kecamatan': 'Kecamatan', 'nama_desa': 'Desa',
        'latitude_desa': 'lat', 'longitude_desa': 'lon',
        'total_pinjaman_kel': 'Total_Pinjaman', 'total_simpanan_kel': 'Total_Simpanan',
        'jumlah_keluarga_pengguna_listrik': 'Jumlah_KK',
        'attractiveness_index': 'Skor_Potensi',
        'max_tipe_usaha': 'Sektor_Dominan',
        'jumlah_lokasi_permukiman_kumuh': 'Risk_Kumuh',
        'bencana_alam': 'Risk_Bencana',
        'jumlah_perkelahian_masyarakat': 'Risk_Konflik'
    }, inplace=True)
    
    # Fill NaN with 0
    num_cols = df.select_dtypes(include=[np.number]).columns
    df[num_cols] = df[num_cols].fillna(0)
    
    # --- B. METRIC CALCULATION ---
    # 1. Saturation (Loan per HH)
    # [FIX] Handle division by zero carefully
    df['Jumlah_KK'] = df['Jumlah_KK'].replace(0, 1) 
    df['Loan_per_HH'] = (df['Total_Pinjaman'] / df['Jumlah_KK']) / 1_000_000 # Juta Rp
    
    # 2. Risk Scoring (Composite)
    # Saturation Risk Contribution
    sat_risk = (df['Loan_per_HH'] / 50.0).clip(0, 1) * 100 
    # Economic Risk Contribution (Inverted Potential)
    max_pot = df['Skor_Potensi'].max()
    if max_pot == 0: max_pot = 1 # Prevent division by zero
    eco_risk = 100 - ((df['Skor_Potensi'] / max_pot) * 100)
    
    # Env/Social Flags
    env_risk = (df['Risk_Kumuh'] > 0).astype(int) * 30 + \
               (df['Risk_Bencana'] > 0).astype(int) * 20 + \
               (df['Risk_Konflik'] > 0).astype(int) * 50
               
    df['Final_Risk_Score'] = (0.3 * sat_risk) + (0.3 * eco_risk) + (0.4 * env_risk)
    
    # [FIX] Handle Infinite values generated by calculations
    df.replace([np.inf, -np.inf], 0, inplace=True)
    
    # 3. Categorization
    def get_risk_cat(x):
        if x >= 60: return 'Critical'
        elif x >= 40: return 'High'
        elif x >= 20: return 'Medium'
        else: return 'Low'
    df['Risk_Category'] = df['Final_Risk_Score'].apply(get_risk_cat)

    # 4. Strategy Quadrant
    avg_pot = df['Skor_Potensi'].mean()
    avg_sat = df['Loan_per_HH'].mean()
    def get_quad(row):
        if row['Skor_Potensi'] >= avg_pot and row['Loan_per_HH'] < avg_sat: return "Hidden Gem (Grow)"
        elif row['Skor_Potensi'] >= avg_pot and row['Loan_per_HH'] >= avg_sat: return "Red Ocean (Compete)"
        elif row['Skor_Potensi'] < avg_pot and row['Loan_per_HH'] >= avg_sat: return "High Risk (Stop)"
        else: return "Dormant (Monitor)"
    df['Strategy_Quadrant'] = df.apply(get_quad, axis=1)

    # 5. Market Sentiment Simulator (Fixed Seed for Stability)
    np.random.seed(42)
    df['Sentiment_Score'] = np.random.uniform(3.5, 4.9, size=len(df))
    df['Review_Count'] = np.random.randint(10, 500, size=len(df))
    
    return df

df = load_data_engine()
if df is None:
    st.error("Data 'Prototype Jawa Tengah.csv' tidak ditemukan.")
    st.stop()

# -----------------------------------------------------------------------------
# 3. GLOBAL SIDEBAR
# -----------------------------------------------------------------------------
st.sidebar.title("🎛️ Geo-Control")
selected_kab = st.sidebar.selectbox("Wilayah (Kabupaten)", df['Kabupaten'].unique())
df_kab = df[df['Kabupaten'] == selected_kab]

selected_kec = st.sidebar.multiselect("Filter Kecamatan", df_kab['Kecamatan'].unique(), default=df_kab['Kecamatan'].unique())
df_filtered = df_kab[df_kab['Kecamatan'].isin(selected_kec)]

st.sidebar.markdown("---")
st.sidebar.caption(f"Total Desa Terpilih: {len(df_filtered)}")

# -----------------------------------------------------------------------------
# 4. TAB ARCHITECTURE
# -----------------------------------------------------------------------------
tab1, tab2, tab3, tab4 = st.tabs([
    "📊 Executive Summary", 
    "🚀 Growth Intelligence", 
    "⚖️ Saturation Deep-Dive", 
    "🛡️ Risk Guardian"
])

# =============================================================================
# TAB 1: EXECUTIVE SUMMARY (High Level View)
# =============================================================================
with tab1:
    st.markdown(f"### 📋 Ringkasan Eksekutif: {selected_kab}")
    
    # Top Level metrics
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        st.metric("Total Exposure", f"Rp {df_filtered['Total_Pinjaman'].sum()/1e9:,.1f} M")
    with c2:
        st.metric("Rata-rata Risk Score", f"{df_filtered['Final_Risk_Score'].mean():.1f}/100")
    with c3:
        gem_count = len(df_filtered[df_filtered['Strategy_Quadrant']=='Hidden Gem (Grow)'])
        st.metric("Potensi 'Hidden Gem'", f"{gem_count} Desa")
    with c4:
        risk_count = len(df_filtered[df_filtered['Risk_Category'].isin(['High', 'Critical'])])
        st.metric("Area Waspada (High Risk)", f"{risk_count} Desa", delta_color="inverse")

    st.markdown("---")
    
    # The "Universe" Chart
    st.subheader("🌌 Peta Strategi Makro (The Strategic Universe)")
    st.caption("Visualisasi ini memetakan seluruh desa berdasarkan potensi vs risiko. Arahkan kursor untuk detail.")
    
    # [FIX] Ensure columns are explicitly numeric types for Altair
    chart_data = df_filtered.copy()
    chart_data['Total_Pinjaman_Scaled'] = chart_data['Total_Pinjaman'] / 1e6 # Scale down for size
    
    chart_univ = alt.Chart(chart_data).mark_circle().encode(
        x=alt.X('Skor_Potensi', title='Potensi Ekonomi (Score)'),
        y=alt.Y('Loan_per_HH', title='Saturasi (Pinjaman Juta/KK)'),
        color=alt.Color('Risk_Category', scale=alt.Scale(domain=['Low','Medium','High','Critical'], range=['green','gold','orange','red'])),
        size=alt.Size('Total_Pinjaman_Scaled', scale=alt.Scale(range=[20, 500]), legend=None),
        tooltip=['Desa','Kecamatan','Risk_Category','Strategy_Quadrant', 'Loan_per_HH', 'Skor_Potensi']
    ).properties(height=500).interactive()
    
    st.altair_chart(chart_univ, use_container_width=True)

# =============================================================================
# TAB 2: GROWTH INTELLIGENCE (Offensive Strategy)
# =============================================================================
with tab2:
    st.markdown("### 🚀 Analisis Potensi Pertumbuhan")
    st.info("Fokus: Menemukan area dengan ekonomi kuat dan sentimen pasar positif.")
    
    col_g1, col_g2 = st.columns([2, 1])
    
    with col_g1:
        st.subheader("📍 Peta Potensi Ekonomi")
        # Map focused on Attractiveness
        chart_map_pot = alt.Chart(df_filtered).mark_circle(size=80).encode(
            longitude='lon', latitude='lat',
            color=alt.Color('Skor_Potensi', scale=alt.Scale(scheme='greens'), title='Skor Potensi'),
            tooltip=['Desa', 'Skor_Potensi', 'Sektor_Dominan']
        ).project('mercator').properties(height=400)
        st.altair_chart(chart_map_pot, use_container_width=True)
        
    with col_g2:
        st.subheader("🏭 Sektor Dominan")
        sector_counts = df_filtered['Sektor_Dominan'].value_counts().reset_index()
        sector_counts.columns = ['Sektor', 'Jumlah Desa']
        
        st.dataframe(sector_counts, hide_index=True, use_container_width=True)
    
    # Market Sentiment Analysis (Simulated)
    st.markdown("---")
    st.subheader("⭐ Market Sentiment (Simulasi Google Maps)")
    
    top_sentiment = df_filtered.sort_values(by='Sentiment_Score', ascending=False).head(10)
    
    st.altair_chart(
        alt.Chart(top_sentiment).mark_bar().encode(
            x=alt.X('Sentiment_Score', domain=[0, 5], title='Rating Rata-rata'),
            y=alt.Y('Desa', sort='-x'),
            color=alt.Color('Review_Count', title='Jml Ulasan'),
            tooltip=['Desa','Sektor_Dominan','Sentiment_Score']
        ).properties(title="Top 10 Desa dengan Rating Usaha Tertinggi"),
        use_container_width=True
    )

# =============================================================================
# TAB 3: SATURATION DEEP-DIVE (Market Share Strategy)
# =============================================================================
with tab3:
    st.markdown("### ⚖️ Analisis Saturasi & Persaingan")
    st.info("Fokus: Mengidentifikasi area jenuh (Red Ocean) vs area kosong (Blue Ocean).")
    
    # Metric Saturation
    c_s1, c_s2 = st.columns(2)
    with c_s1:
        st.subheader("Matriks Persaingan")
        quad_counts = df_filtered['Strategy_Quadrant'].value_counts().reset_index()
        quad_counts.columns = ['Kategori', 'Jumlah Desa']
        
        base = alt.Chart(quad_counts).encode(theta=alt.Theta("Jumlah Desa", stack=True))
        pie = base.mark_arc(outerRadius=120).encode(
            color=alt.Color("Kategori"),
            order=alt.Order("Jumlah Desa", sort="descending"),
            tooltip=["Kategori", "Jumlah Desa"]
        )
        st.altair_chart(pie, use_container_width=True)
        
    with c_s2:
        st.subheader("Top 10 Area 'Red Ocean' (Sangat Jenuh)")
        red_ocean = df_filtered[df_filtered['Strategy_Quadrant'] == 'Red Ocean (Compete)']
        red_ocean_sorted = red_ocean.sort_values(by='Loan_per_HH', ascending=False).head(10)
        st.dataframe(
            red_ocean_sorted[['Desa', 'Kecamatan', 'Loan_per_HH', 'Total_Pinjaman']],
            hide_index=True,
            column_config={"Loan_per_HH": st.column_config.NumberColumn("Pinjaman/KK (Juta)", format="Rp %.1f")}
        )

    st.markdown("#### 🗺️ Heatmap Saturasi")
    st.map(df_filtered, latitude='lat', longitude='lon', size=20, color='#FFA500')
    st.caption("Peta sebaran titik desa. Fokus pada densitas titik di area tertentu.")

# =============================================================================
# TAB 4: RISK GUARDIAN (Defensive Strategy)
# =============================================================================
with tab4:
    st.markdown("### 🛡️ Profil Risiko & Mitigasi")
    st.error("Fokus: Peringatan Dini (EWS) untuk area dengan risiko gagal bayar tinggi.")
    
    # Risk Factor Breakdown
    col_r1, col_r2 = st.columns([2, 1])
    
    with col_r1:
        st.subheader("📍 Zona Bahaya (Risk Heatmap)")
        # Red map for high risk
        risk_map = alt.Chart(df_filtered).mark_circle(size=80).encode(
            longitude='lon', latitude='lat',
            color=alt.Color('Final_Risk_Score', scale=alt.Scale(scheme='reds'), title='Score Risiko'),
            tooltip=['Desa', 'Risk_Category', 'Final_Risk_Score']
        ).project('mercator').properties(height=400)
        st.altair_chart(risk_map, use_container_width=True)
        
    with col_r2:
        st.subheader("🚨 Pemicu Risiko Utama")
        risk_summary = pd.DataFrame({
            'Faktor': ['Konflik Sosial', 'Bencana Alam', 'Kumuh', 'Over-Indebted'],
            'Jml Desa': [
                (df_filtered['Risk_Konflik']>0).sum(),
                (df_filtered['Risk_Bencana']>0).sum(),
                (df_filtered['Risk_Kumuh']>0).sum(),
                (df_filtered['Loan_per_HH']>50).sum() # Asumsi >50jt/KK over
            ]
        })
        st.bar_chart(risk_summary.set_index('Faktor'))

    # Detailed Risk Table
    st.markdown("### 📋 Daftar Hitam & Pengawasan Khusus (Watchlist)")
    
    high_risk_df = df_filtered[df_filtered['Risk_Category'].isin(['High', 'Critical'])].sort_values(by='Final_Risk_Score', ascending=False)
    
    def highlight_critical(val):
        return 'background-color: #ffcccc' if val == 'Critical' else ''

    st.dataframe(
        high_risk_df[['Desa', 'Kecamatan', 'Risk_Category', 'Final_Risk_Score', 'Risk_Konflik', 'Risk_Bencana']],
        hide_index=True,
        use_container_width=True,
        column_config={
            "Final_Risk_Score": st.column_config.ProgressColumn("Skor Risiko", min_value=0, max_value=100, format="%.1f"),
            "Risk_Konflik": st.column_config.CheckboxColumn("Konflik?"),
            "Risk_Bencana": st.column_config.CheckboxColumn("Bencana?")
        }
    )
    
    # Automated Policy Logic
    st.info("""
    **Rekomendasi Kebijakan Kredit (Automated Policy):**
    * 🔴 **Critical:** Stop Selling. Fokus Collection.
    * 🟠 **High:** Batasi LTV max 50%. Wajib Agunan Tetap.
    * 🟡 **Medium:** Verifikasi lapis dua (on-the-spot check).
    * 🟢 **Low:** Pre-approved limit & Instant Approval.
    """)

# Footer
st.markdown("---")
st.caption("Developed by Tio Brain | Enterprise Geo-Intelligence Framework v5.1")
